version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./rails:/usr/src/app
      - gem_cache:/gems
      - tmp:/usr/src/app/tmp
    env_file:
      - .env/development/web
  composer:
    image: composer:1.9.3
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - ./php:/app
  php:
    image: php:7.4-cli
    volumes:
      - ./php:/app
    working_dir: /app
  phpunit:
    image: php:7.4-cli
    volumes:
      - ./php:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
volumes:
  gem_cache:
  tmp:
